package:
  name: gke-gcloud-auth-plugin
  version: 0.1.0
  epoch: 0
  description: 'kubectl plugin for GKE authentication'
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - kubectl

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/kubernetes/cloud-provider-gcp/archive/refs/tags/auth-provider-gcp/v${{package.version}}.tar.gz
      expected-sha256: 6587c2a9f24f314e13a8dafa62e2199493031365556b8d6455a40832cc87782f

  - uses: go/build
    with:
      packages: ./cmd/gke-gcloud-auth-plugin
      output: gke-gcloud-auth-plugin
      # TODO(mattmoor): Consider adding all of these:
      # https://github.com/kubernetes/cloud-provider-gcp/blob/e64cf3b0fcb1958cee1fe55d7e30f4573c34bf4e/defs/version.bzl#L38
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes/cloud-provider-gcp
    strip-prefix: auth-provider-gcp/v
    tag-filter: auth-provider-gcp/v
    use-tag: true
